# Generated by Django 4.0b1 on 2021-11-19 16:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bonus',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('reason', models.CharField(max_length=128, unique=True, verbose_name='Причина')),
                ('count', models.IntegerField(verbose_name='Количество')),
            ],
            options={
                'verbose_name': 'История бонусов',
                'verbose_name_plural': 'История бонусов',
                'db_table': 'bonus_history',
                'ordering': ['id', 'user', 'reason', 'count'],
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('date', models.DateField(verbose_name='Дата')),
                ('time', models.TimeField(verbose_name='Время')),
                ('payment_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='users.paymenttype', verbose_name='Вид оплаты')),
                ('storage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='products.storage', verbose_name='Склад')),
            ],
            options={
                'verbose_name': 'Заказ',
                'verbose_name_plural': 'Заказы',
                'db_table': 'order',
                'ordering': ['id', 'user', 'date', 'time', 'payment_type', 'storage'],
            },
        ),
        migrations.CreateModel(
            name='OrderProducts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.PositiveIntegerField(verbose_name='Количество')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_products', to='users.order', verbose_name='Заказ')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_products', to='products.product', verbose_name='Товар')),
            ],
            options={
                'verbose_name': 'Товар заказа',
                'verbose_name_plural': 'Товары заказа',
                'db_table': 'order_products',
                'ordering': ['order', 'product'],
                'unique_together': {('product', 'order')},
            },
        ),
        migrations.DeleteModel(
            name='BonusType',
        ),
        migrations.AlterModelOptions(
            name='user',
            options={'ordering': ['login', 'email', 'phone', 'birthday', 'is_active', 'is_staff'], 'verbose_name': 'Пользователь', 'verbose_name_plural': 'Пользователи'},
        ),
        migrations.AddField(
            model_name='order',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='users.user', verbose_name='Покупатель'),
        ),
        migrations.AddField(
            model_name='bonus',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bonuses', to='users.user', verbose_name='Пользователь'),
        ),
    ]
