# Generated by Django 4.0rc1 on 2021-12-17 16:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_user_first_name_user_last_name'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='order',
            options={'verbose_name': 'Заказ', 'verbose_name_plural': 'Заказы'},
        ),
        migrations.RemoveField(
            model_name='order',
            name='payment_type',
        ),
        migrations.DeleteModel(
            name='PaymentType',
        ),
    ]
