# Generated by Django 4.0rc1 on 2021-12-17 16:48

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_order_options_remove_order_payment_type_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='order',
            options={'ordering': ['id', 'user', 'datetime', 'payment_type', 'storage'], 'verbose_name': 'Заказ', 'verbose_name_plural': 'Заказы'},
        ),
        migrations.RemoveField(
            model_name='order',
            name='date',
        ),
        migrations.RemoveField(
            model_name='order',
            name='time',
        ),
        migrations.AddField(
            model_name='order',
            name='datetime',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата и время'),
        ),
        migrations.AddField(
            model_name='order',
            name='payment_type',
            field=models.CharField(choices=[('CASH_UPON_RECEIPT', 'Наличными при получении'), ('CARD_ONLINE', 'Картой онлайн')], default='CASH_UPON_RECEIPT', max_length=20),
        ),
    ]
