export enum BasketActionsEnum {
    TOGGLE_BASKET = "BASKET_ACTION__TOGGLE_BASKET",
    CLOSE_BASKET = "BASKET_ACTION__CLOSE_BASKET",
    CHANGE_PRODUCT_COUNT = "BASKET_ACTION__CHANGE_PRODUCT_COUNT",
    ADD_PRODUCT = "BASKET_ACTION__ADD_PRODUCT",
    CLEAR_BASKET = "BASKET_ACTION__CLEAR_BASKET",
    OPEN_BASKET = "BASKET_ACTION__OPEN_BASKET",
}
