PAYMENT_TYPE__CASH_UPON_RECEIPT = "CASH_UPON_RECEIPT"
PAYMENT_TYPE__CARD_ONLINE = "CARD_ONLINE"

PAYMENT_TYPE = [
    (PAYMENT_TYPE__CASH_UPON_RECEIPT, "Наличными при получении"),
    (PAYMENT_TYPE__CARD_ONLINE, "Картой онлайн"),
]
